logging:
  level:
    root: DEBUG

google:    
    client:
      clientId: 55635804291-3jra80gdoe38doclrihauin01c74h1pu.apps.googleusercontent.com
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
        - https://www.googleapis.com/auth/drive
    resource:
        id: GOOGLE 
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        preferTokenInfo: false

        
github:
  client:
    clientId: 20ce4acc770aecb48cb7
    clientSecret: ${GITHUB_CLIENT_SECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    id: GITHUB
    userInfoUri: https://api.github.com/user 


http:
    mappers:
        jsonPrettyPrint: true
    

spring:
  datasource:
        jdbcUrl: jdbc:postgresql://ec2-54-243-211-197.compute-1.amazonaws.com:5432/d96e56s8l7b330?sslmode=require
        username: wpqkyulvdisaoi
        password: c547f06858c8ed4a509232761ceb1a0e0662e7269cd66c969547f6abac3ea757

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://pdb-registry.herokuapp.com/eureka/}
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}}

    
---
spring:
  profiles: local
  datasource:
        jdbcUrl: jdbc:postgresql://ec2-54-243-211-197.compute-1.amazonaws.com:5432/d96e56s8l7b330?sslmode=require
        username: wpqkyulvdisaoi
        password: c547f06858c8ed4a509232761ceb1a0e0662e7269cd66c969547f6abac3ea757

google:    
    client:
      clientId: 55635804291-3jra80gdoe38doclrihauin01c74h1pu.apps.googleusercontent.com
      clientSecret: ${GOOGLE_CLIENT_SECRET}
        
github:
  client:
    clientId: 20ce4acc770aecb48cb7
    clientSecret: ${GITHUB_CLIENT_SECRET}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    
proxy:
  auth:
    routes:
      pdb-auth: oauth2
      