management:
    security:
        enabled : false
        

    
ribbon:
  eureka:
    enabled: true
  restclient:
    enabled: true
    
---
spring:
  profiles: local
  
server:
    port: 9998
    context-path: /pdb-gateway
    
security:
  oauth2:
    client:
      client-id: PDB-GATEWAY
      client-secret: PDB-GATEWAY
      access-token-uri: http://localhost:8889/oauth/token
      user-authorization-uri: http://localhost:8889/oauth/authorize
      scope: read
    resource:
      user-info-uri: http://localhost:8889/me
        

    
zuul:
    ignoredServices: '*'
    routes:
        user:
            path: /api/**
            sensitiveHeaders:
            serviceId: pdb-auth
            stripPrefix: true    
        drive:
            path: /api-drive/**
            sensitiveHeaders:
            serviceId: pdb-googleResourceServer
        github:
            path: /api-github/**
            sensitiveHeaders:
            serviceId: pdb-githubResourceServer
        