management:
    security:
        enabled : false
        
eureka:
  instance:
    hostname: pdb-google.herokuapp.com   

pdb:
    auth:
        client:
            google:
                secret: ${PDB-GOOGLE}
            check_token:
                url: http://pdb-auth/oauth/check_token
---
spring:
  profiles: local
        
server:
    port: 7777
    context-path: /pdb-google

