logging:
  level:
    root: DEBUG
    
# H2
spring:
    h2:
        console:
            enabled: true
            path: /h2

---
spring:
  profiles: local   
  datasource:
        url: jdbc:h2:tcp://localhost/~/test
        username: sa
        password:
        driver-class-name: org.h2.Driver
        type: H2

server:
    port: 5555

 