management:
    security:
        enabled : false

---
spring:
  profiles: local

server:
    port: 8889
    
pdb:
    app:
        homeUrl: http://pdb-gateway/pdb-gateway/home
    auth:
        client:
            google:
                secret: PDB-GOOGLE
            github:
                secret: PDB-GITHUB
            gateway:
                secret: PDB-GATEWAY    

eureka:
  instance:
    metadataMap:
        management:
            context-path: 
    statusPageUrlPath: /info
    healthCheckUrlPath: /health     