management:
    security:
        enabled : false

pdb:
    app:
        homeUrl: http://pdb-gateway/home
    auth:
        client:
            google:
                secret: ${PDB-GOOGLE}
            github:
                secret: ${PDB-GITHUB}
            gateway:
                secret: ${PDB-GATEWAY}

eureka:
  instance:
    hostname: pdb-auth.herokuapp.com
                          
---
spring:
  profiles: local

server:
    port: 8889
    

 